# Generated by Django 3.2.7 on 2021-12-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codefun', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
