# Generated by Django 3.2.7 on 2021-12-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codefun', '0003_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='postchoice',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
