# Generated by Django 3.2.7 on 2021-12-18 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codefun', '0007_alter_code_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coder', to=settings.AUTH_USER_MODEL),
        ),
    ]
