# Generated by Django 3.2.7 on 2021-12-18 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codefun', '0009_alter_code_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='coder', to='codefun.user'),
            preserve_default=False,
        ),
    ]
