# Generated by Django 3.2.7 on 2021-12-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codefun', '0010_alter_code_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email',
            field=models.BooleanField(default=False),
        ),
    ]
